NB_URL = ''
NB_API_TOKEN = ''

ZABBIX_URL = ''
ZABBIX_USER = ''
ZABBIX_PASS = ''

COMMUNITY = ''

DONT_ASK = False

LOG_FILE = '/var/log/netbox-to-zabbix.log'
LOG_LEVEL = 'INFO'

NB_CF_HW_MPLS = 'Huawei MPLS'
NB_CF_CISCO_BRAS_ASR_PPPOE = 'Cisco ASR BRAS PPPoE'
NB_CF_CISCO_BRAS_ASR_B2B = 'Cisco ASR BRAS B2B'
NB_CF_CISCO_BRAS_IOS_B2B = 'Cisco IOS BRAS B2B'
NB_CF_JUNIPER_BRAS_IPOE = 'Juniper BRAS IPoE'
NB_CF_JUNIPER_BRAS_BNG = 'Juniper BNG'
NB_CF_JUNIPER_MX_CORE = 'Juniper MX Core'
NB_CF_JUNIPER_MX104_CORE = 'Juniper MX104 Core'

TEMPLATE_HUAWEI_MPLS_ID = 0
TEMPLATE_CISCO_BRAS_ASR_B2B_ID = 0
TEMPLATE_CISCO_BRAS_ASR_PPPOE_ID = 0
TEMPLATE_CISCO_BRAS_IOS_B2B_ID = 0
TEMPLATE_JUNIPER_BRAS_BNG_ID = 0
TEMPLATE_JUNIPER_BRAS_IPOE_ID = 0
TEMPLATE_JUNIPER_MX_CORE_ID = 0
TEMPLATE_JUNIPER_MX_104_CORE_ID = 0

GROUP_JUNIPER_BRAS_ID = 0
GROUP_HUAWEI_MPLS_ID = 0
GROUP_JUNIPER_CORE_ID = 0
GROUP_CISCO_BRAS_ID = 0
GROUP_NBSYNC_ID = 0

CF_MAP = {
    # NB_CF_HW_MPLS: {
    #     'groups': [GROUP_HUAWEI_MPLS_ID],
    #     'templates': [TEMPLATE_HUAWEI_MPLS_ID],
    # },
    NB_CF_CISCO_BRAS_ASR_PPPOE: {
        'groups': [GROUP_CISCO_BRAS_ID],
        'templates': [TEMPLATE_CISCO_BRAS_ASR_PPPOE_ID],
    },
    NB_CF_CISCO_BRAS_ASR_B2B: {
        'groups': [GROUP_CISCO_BRAS_ID],
        'templates': [TEMPLATE_CISCO_BRAS_ASR_B2B_ID],
    },
    NB_CF_CISCO_BRAS_IOS_B2B: {
        'groups': [GROUP_CISCO_BRAS_ID],
        'templates': [TEMPLATE_CISCO_BRAS_IOS_B2B_ID],
    },
    NB_CF_JUNIPER_BRAS_BNG: {
        'groups': [GROUP_JUNIPER_BRAS_ID],
        'templates': [TEMPLATE_JUNIPER_BRAS_BNG_ID],
    },
    NB_CF_JUNIPER_BRAS_IPOE: {
        'groups': [GROUP_JUNIPER_BRAS_ID],
        'templates': [TEMPLATE_JUNIPER_BRAS_IPOE_ID],
    },
    NB_CF_JUNIPER_MX_CORE: {
        'groups': [GROUP_JUNIPER_CORE_ID],
        'templates': [TEMPLATE_JUNIPER_MX_CORE_ID],
    },
    NB_CF_JUNIPER_MX104_CORE: {
        'groups': [GROUP_JUNIPER_CORE_ID],
        'templates': [TEMPLATE_JUNIPER_MX_CORE_ID, TEMPLATE_JUNIPER_MX_104_CORE_ID],
    },
}
